apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dotglitch.dev-ingress
spec:
  entryPoints:
   - web
  routes:
    - match: Host(`dotglitch.dev`) || Host(`www.dotglitch.dev`)
      kind: Rule
      services:
      - name: dotglitch-server
        port: 80

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dotglitch.dev-secure-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dotglitch.dev`) || Host(`www.dotglitch.dev`)
      services:
        - name: dotglitch-server
          port: 80
  tls:
    secretName: dotglitch.dev-tls

---

apiVersion: v1
kind: Service
metadata:
  name: dotglitch-server
spec:
  selector:
    app: dotglitch-server
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotglitch-server
spec:
  selector:
    matchLabels:
      app: dotglitch-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dotglitch-server
    spec:
      containers:
      - name: dotglitch
        image: harbor.dotglitch.dev/library/dotglitch:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-key

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dotglitch.dev
spec:
  commonName: dotglitch.dev
  dnsNames:
    - dotglitch.dev
    - www.dotglitch.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: dotglitch.dev-tls


